ALTER TABLE document_type_settings
  ADD COLUMN IF NOT EXISTS search_profile TEXT NOT NULL DEFAULT 'generic',
  ADD COLUMN IF NOT EXISTS prefer_content_matches BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS prefer_document_focus BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS require_focus_terms BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS prefer_adjacent_sections BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS adjacent_section_window INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS small_to_big_window INTEGER NOT NULL DEFAULT 1;